#Python Assignment From Gaone Gee Mokhawa Student Number 14M8501
#7.Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#1,2,3,5,8,13,21,34,55,89,..

#by considering the terms in the Fibonacci sequence whose values do not exceed 4000, this program finds the sums of the multiples of 5.


a, b = 0, 1
total=0
for i in range(15):
    if a%5==0:
        total=total+a
        a, b = b, a + b
    print total     
